### ISSUE TITLE
Support TTS on Linux with espeak

### ISSUE THREAD

**Issue by techygrrrl** [techygrrrl/timerrr#1]
This function is right now Mac-only:  https://github.com/techygrrrl/timerrr/blob/ca42818c2e9645791b8c007dc84339da1315db1f/models/timer.go#L96

The results of trying to execute an unknown command via cobra is uncertain. 

Add support for espeak on Linux.

**Comment by wissam** [comment]
I am taking care of this

**Comment by techygrrrl** [comment]
Closed by https://github.com/techygrrrl/timerrr/pull/8
