### ISSUE TITLE
Tests not working on linux locally

### ISSUE THREAD

**Issue by AdjectiveAllison** [techygrrrl/timerrr#10]
I was here and got an error: https://github.com/techygrrrl/timerrr/blob/main/CONTRIBUTING.md#-testing
It looks like the tests were made for running inside of the CI runner with hardcoded runner paths. I'm unsure if it would be better to make them work for local setups or use something like https://github.com/nektos/act to test locally instead.

**Comment by AdjectiveAllison** [comment]
https://github.com/techygrrrl/timerrr/pull/11

There is a quick fix for supporting both my local linux setup and the runner(supposedly).

**Comment by techygrrrl** [comment]
Closed by #11 #14 – thank you @AdjectiveAllison
